### ISSUE TITLE
Populate database with Fetched contest data

### ISSUE THREAD

**Issue by dr0pdb** [Njack-IITP/IITP-Connect#13]
Populate the database with the fetched contest data. Implement insert,query and delete operations.

**Comment by VisheshVadhera** [comment]
For database, you can consider using [Room](https://developer.android.com/topic/libraries/architecture/room.html) instead of Content Providers. Has a better API and is way easier to use than Content Providers.

**Comment by dr0pdb** [comment]
@VisheshVadhera Actually the code for ```Content Providers``` is already implemented in a similar project. Hence it's much easier to migrate the code rather than using ```Room``` from scratch.
