### ISSUE TITLE
Add timetable info in the application

### ISSUE THREAD

**Issue by dr0pdb** [Njack-IITP/IITP-Connect#144]
**Is your feature request related to a problem? Please describe.**
Now that we have the backend for timetables, we can integrate into the application.
Add a new module which fetches the timetable of the user's branch and year and displays it in a nice UI.

**Comment by nikhilbansal97** [comment]
I would like to work on this

**Comment by dr0pdb** [comment]
@nikhilbansal97 Hi, we'll have to wait for some time before we can work on this. I would suggest you work on #116.

**Comment by nikhilbansal97** [comment]
@srv-twry Okay, I'll work on #116 👍 
May I know what is the blocker for this issue??

**Comment by dr0pdb** [comment]
Yeah, we are yet to decide on the schema of the firebase database and we'll need some time for it.

**Comment by nikhilbansal97** [comment]
Okay, cool. No problem 👍
