### ISSUE TITLE
Show Profile option only when the user is logged in

### ISSUE THREAD

**Issue by dr0pdb** [Njack-IITP/IITP-Connect#164]
## Current behavior
Right now, the "Profile" button on the side menu is shown even when the user isn't signed in. When we try to open the profile a toast is shown saying that "You need to login first".

## Required behavior
Only show the button when the user is signed in.

**Comment by nikhilbansal97** [comment]
I would like to work in this issue

**Comment by dr0pdb** [comment]
@nikhilbansal97 Unfortunately @kartikarora has opened a PR for it(although he shouldn't have). I guess you can work on other issues. :)

**Comment by nikhilbansal97** [comment]
@srv-twry I would suggest you add a `in progress` label on the issues so that other people know if it is free to claim or not.

**Comment by kartikarora** [comment]
Apologies for hijacking this issue.
