### ISSUE TITLE
Write unit tests for ContestDetailRepository

### ISSUE THREAD

**Issue by dr0pdb** [Njack-IITP/IITP-Connect#169]
We need to add unit tests to test the functionality of the ContestDetailRepository.

**Comment by PranavBhatia** [comment]
Can I work on this issue please?

**Comment by dr0pdb** [comment]
@PranavBhatia Sure.
In case you need some sort of reference, you should be able to find them here: https://github.com/fossasia/open-event-orga-app/tree/development/app/src/test/java/com/eventyay/organizer/data/repository

**Comment by PranavBhatia** [comment]
Thanks a lot for the reference, will finish working on this issue by tomorrow night (EDT).
