### ISSUE TITLE
Use Retrofit instead of Volley to make network requests. 

### ISSUE THREAD

**Issue by VisheshVadhera** [Njack-IITP/IITP-Connect#17]

**Comment by dr0pdb** [comment]
@VisheshVadhera As i said [here](https://github.com/Njack-IITP/IITP-Connect/issues/13), the code is already implemented using ```Volley```. Hence no point using ```Retrofit``` for it. ```Retrofit``` would definitely be used for future network requests. :smile:

**Comment by VisheshVadhera** [comment]
Why would you want to use a library that is no longer the industry standard? I can help you easily migrate the code base to Retrofit, which is thousand times better than Volley and is way more powerful and easier to use than Volley. And frankly speaking the code which you are taking about, which uses Volley, is just a single class file (NetworkUtils) containing a bunch of methods. So it's a fairly trivial task to switch to Retrofit.

**Comment by dr0pdb** [comment]
@VisheshVadhera Sure , You can go ahead and submit a PR after switching to Retrofit. :smile:
