### ISSUE TITLE
Write unit tests for ProfileRepository

### ISSUE THREAD

**Issue by dr0pdb** [Njack-IITP/IITP-Connect#171]
Write unit tests for ProfileRepository.
In case you need some sort of reference, you should be able to find them here: https://github.com/fossasia/open-event-orga-app/tree/development/app/src/test/java/com/eventyay/organizer/data/repository

**Comment by reevee-codes** [comment]
I want to try to do this!

**Comment by dr0pdb** [comment]
@432hb345 Yes, please go ahead. You can check the reference that I have suggested in case you're stuck. Good luck!

**Comment by jguerrerope** [comment]
HI @srv-twry I've make a pr request for this issue 😄
