### ISSUE TITLE
Add build status badge

### ISSUE THREAD

**Issue by chiragw15** [Njack-IITP/IITP-Connect#35]
Add build status badge in readme file to show status of travis build.

**Comment by 0x48piraj** [comment]
I am on it ! :smiley:

**Comment by 0x48piraj** [comment]
As the Issue says, "**Add build status badge in readme file to show status of travis build.**"
I just added the status badge.

Here's my PR [#38](https://github.com/Njack-IITP/IITP-Connect/pull/38) :+1: 

> It's my second day at PR's. Hope you like it :smile:

**Comment by chiragw15** [comment]
@0x48piraj Please work on unassigned issues. The PR for this issue is already opened. I think you can see it. No need of stupidly opening PRs just to get a hacktoberfest T-shirt. If you seriously want to work on this project, you are most welcome. Otherwise, please stop spamming. Cheers.

**Comment by diegorramos** [comment]
@chiragw15 Added badge PR by #40

**Comment by 0x48piraj** [comment]
That's the same `error` which I got and closed this PR @Polovinsky 
![image](https://user-images.githubusercontent.com/5800726/32103697-3242e026-bb3f-11e7-8aeb-4bce1102de81.png)

**Comment by 0x48piraj** [comment]
> No need of stupidly opening PRs just to get a hacktoberfest T-shirt.

I'm totally new to this community and have already submitted 5 PR's and all are accepted/merged :+1: 

Think before saying anything @chiragw15 


![image](https://user-images.githubusercontent.com/5800726/32103817-9df533f0-bb3f-11e7-9c05-985ad96eb4dd.png)
