### ISSUE TITLE
Add swipe to refresh in Coding Calendar Home Activity

### ISSUE THREAD

**Issue by arundhatigupta** [Njack-IITP/IITP-Connect#52]
Currently the user is not allowed to refresh this page. Adding swipe to refresh will allow the user to refresh the Coding Calendar home page.

![iitp_2](https://user-images.githubusercontent.com/30979369/34944728-afcec5d4-fa26-11e7-8a42-034fed5b7349.jpg)

**Comment by dr0pdb** [comment]
@arundhati24 Let's work on it later. Right now, we need to get the app to a release state and hence we should focus more on new features such as Attendance manager, LiveFacebook feed etc.

**Comment by dr0pdb** [comment]
Fixed.
