### ISSUE TITLE
Use Timber for logging

### ISSUE THREAD

**Issue by dr0pdb** [Njack-IITP/IITP-Connect#55]
**Actual Behaviour**

Right now we are using the default logging component provided by the Android SDK.

**Expected Behaviour**

We should use Timber for logging because it's very popular and is the industry standard.
Refactor all logging statements(if any) to use Timber 

**Would you like to work on the issue?**

Yes

**Comment by jafjdev** [comment]
Are you working here? i would like to take this issue

**Comment by dr0pdb** [comment]
No, Please go ahead with this.
