### ISSUE TITLE
Use lombok to remove boiler plate code in POJOs

### ISSUE THREAD

**Issue by dr0pdb** [Njack-IITP/IITP-Connect#56]
**Actual Behaviour**

There is a lot of boilerplate code inside the POJOs.

**Expected Behaviour**

These can be replaced by using [Lombok](https://projectlombok.org/)

**Comment by arundhatigupta** [comment]
@srv-twry  may i work on this?

**Comment by mayank8318** [comment]
@arundhati24 Go ahead :)

**Comment by arundhatigupta** [comment]
@srv-twry  @mayank8318  When I add the dependency for lombok, i get the following error : 

Dependency :
![lombok_dependency](https://user-images.githubusercontent.com/30979369/35430369-fbeb55ac-029d-11e8-88dc-ab04475ce13e.png)

Error :
![lombok_failed_to_resolve](https://user-images.githubusercontent.com/30979369/35430390-063fd4d8-029e-11e8-9217-5f8ed6c0f00a.png)


Earlier the annotation processing was disabled. I enabled it in Settings. Even then I get the same error.  I also tried using older version but that too didn't work. Please see if you could help me with this.

**Comment by arundhatigupta** [comment]
@srv-twry @mayank8318  Please review the pull request.
