### ISSUE TITLE
Write ViewModel tests

### ISSUE THREAD

**Issue by dr0pdb** [Njack-IITP/IITP-Connect#60]
**Expected Behaviour**

Write ViewModel tests for 
- [x] CodingCalendarViewModel
- [x] ContestDetailViewModel

**Parent issue**

#48

**Comment by jguerrerope** [comment]
Hi @srv-try, to fix this issue it would be better to split in two task. You can check the changes better.  What do you think ?

**Comment by dr0pdb** [comment]
@jguerrerope Yes, that is fine. Please create two issues and you can work on them. :)

**Comment by jguerrerope** [comment]
@srv-try I've made a mistake when I've created the issues, sorry for that 😭
