### ISSUE TITLE
Setup UI for Attendance manager

### ISSUE THREAD

**Issue by dr0pdb** [Njack-IITP/IITP-Connect#71]
**Expected Behaviour**

Setup UI for Attendance manager

To be treated as a parent issue.

**Comment by aamarill** [comment]
Hello,

I am looking to make my first open source contribution. Is this a good issue to take on?
If not, feel free to point me other issues that might be good for someone that's new to open source.
Thanks!

**Comment by dr0pdb** [comment]
Hi @aamarill , Welcome. 
Yes, this is a good issue to take on. 
However since you're looking for your first open source contribution, I would suggest taking other issues which are even easier than this.
#55 
#74 
#49 
Moreover this issue has been marked as Later. We would prefer if you work on issues which are our current priority. :smile:

**Comment by jafjdev** [comment]
How should the UI looks like?

**Comment by dr0pdb** [comment]
@jafjdev , This is not a priority right now. We want to first make sure we have setup coding calendar correctly. This issue has been marked as ```Later``` hence we will tackle this later

**Comment by aamarill** [comment]
@srv-twry thank you for the info! I didn't realize the entire project was written in Java which I don't know at the moment. Best of luck! 😄
