### ISSUE TITLE
Use Android data binding framework

### ISSUE THREAD

**Issue by dr0pdb** [Njack-IITP/IITP-Connect#76]
**Actual Behaviour**

Right now we are using Butterknife to reduce the boilerplate code for view bindings.

**Expected Behaviour**

The official Data binding framework is extremely powerful and supports two way data binding as well. Replace the usage of Butterknife and refactor to use the data binding library.

**Comment by jafjdev** [comment]
i'll take this issue

**Comment by dr0pdb** [comment]
Solved.
