### ISSUE TITLE
Introduce Dependency injection using Dagger2

### ISSUE THREAD

**Issue by dr0pdb** [Njack-IITP/IITP-Connect#87]
### Feature Request

**Feature Description**

Right now we aren't using DI. It should be introduced in the project as it allows for better decoupling.

**Comment by ldps21** [comment]
Hello, Im currently working on this issue.

**Comment by ldps21** [comment]
@srv-twry could you be more specific or elaborate on your request?

**Comment by dr0pdb** [comment]
@ldps21 Are you familiar with the term dependency injection ?
Right now we aren't using it in our application. It means the app isn't testable and maintainable. We would like to use the Dagger2 library to help use DI. 
Please follow this series to understand dependeny injection and dagger: https://www.youtube.com/playlist?list=PLuR1PJnGR-Ih-HXnGSpnqjdhdvqcwhfFU

**Comment by ldps21** [comment]
@srv-twry thank you.

**Comment by dr0pdb** [comment]
Solved.
