### ISSUE TITLE
Part 2: Authentication using Firebase

### ISSUE THREAD

**Issue by dr0pdb** [Njack-IITP/IITP-Connect#98]
**Is your feature request related to a problem? Please describe.**
A little bit of setup has already been done for Firebase authentication. We need to take it forwards.

**Comment by Sjsingh101** [comment]
@srv-twry sir why you want to authenticate everytime from firebase i will make app slow instead using shared preferences is a good option isn't it
by the way i am new to open source so please guide me sir

**Comment by dr0pdb** [comment]
1. Please don't call me sir.
2. If you're a beginner, then this issue is not for you. Please try the issues labeled with `beginner level`.
3. > why you want to authenticate everytime from firebase it will make app slow instead using shared preferences is a good option isn't it

Shared preferences are stored as an xml file. It is not secure to store passwords in Shared preferences. Firebase auth won't slow down. The user will login just once in order to use it for a session.
